spring:
    datasource:
        driverClassName:  com.mysql.jdbc.Driver
    profiles:
      active: dev



server:
    port: 1102



wechat:
    hbuas:
        token: comaqhitoken20180303
        appId: wx4a3edc9b04eb343c



